<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Types.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core"/>
    </ItemGroup>
</Project>
